[[plugins]]
repo = 'tyru/empty-prompt.vim'
depends = ['vital.vim']
hook_add = '''
  " : works as <C-w>:
  autocmd MyAutoGroup VimEnter * call empty_prompt#map(#{lhs: ':', rhs: '<C-w>:'})
  " <Esc> works as <C-w>N
  autocmd MyAutoGroup VimEnter * call empty_prompt#map(#{lhs: '<Esc>', rhs: '<C-w>N'})
'''
hook_post_source = '''
  let s:prompt = {}

  let s:prompt['cmd'] = '>'
  let s:prompt['nix'] = '$'

  let s:starship_config = expand(g:user.dir.config_home . '/starship.toml')
  let s:starship = {}
  if filereadable(s:starship_config)
    let s:TOML = g:V.import('Text.TOML')
    let s:starship = s:TOML.parse_file(s:starship_config)
    unlet s:TOML
  endif

  let s:prompt['starship'] = '❯'
  if has_key(s:starship,'character')
    if has_key(s:starship.character, 'symbol')
      let s:prompt['starship'] = s:starship.character.symbol
    endif
  endif

  let s:result = '\(' . escape(join(values(s:prompt), '|'), '\|$')  . '\)\s*$'

  let g:empty_prompt#pattern = s:result
  unlet s:result
'''
