[[plugins]]
repo = 'haya14busa/incsearch.vim'
[[plugins]]
repo = 'haya14busa/incsearch-fuzzy.vim'

[[plugins]]
repo = 'haya14busa/incsearch-migemo.vim'
[[plugins]]
repo = 'haya14busa/vim-migemo'
hook_add = '''
    map / <Plug>(incsearch-migemo-/)
    map ? <Plug>(incsearch-migemo-?)
    map g/ <Plug>(incsearch-migemo-stay)
    map m/ <Plug>(incsearch-forward)
    map m? <Plug>(incsearch-backward)
    map mg/ <Plug>(incsearch-stay) 
'''