[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'php', 'vue']
hook_add = '''
let g:closetag_filenames = '*.html,*.php,*.vue'
'''

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python']

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTree', 'NERDTreeToggle', 'NERDTreeTabsToggle', 'NERDTreeTabsFind', 'NERDTreeFind']
depends = ['vim-nerdtree-tabs', 'nerdtree-git-plugin']
hook_add = '''
  let g:NERDTreeIgnore = ['\.swp$', '\.meta$']
  let g:NERDTreeQuitOnOpen = 1
  let g:NERDTreeMapOpenInTab = '<ENTER>'
  let g:NERDTreeShowHidden = 1
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
  let g:nerdtree_tabs_autofind = 1
  nnoremap <silent> <C-n> :NERDTreeTabsClose<CR>
  nnoremap <silent> <C-e> :NERDTreeFocusToggle<CR>
  autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | execute 'NERDTreeTabsOpen' | endif
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
hook_add = '''
let g:NERDTreeGitStatusUseNerdFonts = 1
let g:NERDTreeGitStatusConcealBrackets = 1
'''

[[plugins]]
repo = 'sharat87/roast.vim'
on_ft = ['roast']

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app && yarn install"'

[[plugins]]
repo = 'puremourning/vimspector'
on_ft = ['python', 'javascript', 'typescript']
build = './install_gadget.py --enable-python --force-enable-node'
hook_add = '''
let g:vimspector_enable_mappings = 'VISUAL_STUDIO'
nnoremap <silent> <F3> :VimspectorReset<CR>
'''
