hook_add = '''
    let alphabets = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]
    for k in alphabets
        execute "map /".k." <Plug>(incsearch-migemo-/)".k
        execute "map ?".k." <Plug>(incsearch-migemo-?)".k
        execute "map g/".k." <Plug>(incsearch-migemo-stay)".k
    endfor
    let alphabetsu = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"]
    for k in alphabetsu
        execute "map /".k." <Plug>(incsearch-forward)".k
        execute "map ?".k." <Plug>(incsearch-backward)".k
        execute "map g/".k." <Plug>(incsearch-stay)".k
    endfor
    map / <Nop>
    map ? <Nop>
    map g/ <Nop>
'''