[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
  " フォルダアイコンの表示をON
  let g:WebDevIconsUnicodeDecorateFolderNodes = 1
  " let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = ''
  " ? let g:WebDevIconsDefaultFolderOpenSymbol = ''

  let g:NERDTreeDirArrowExpandable  = nr2char(0xf0da) "  nf-fa-caret_right
  let g:NERDTreeDirArrowCollapsible = nr2char(0xf0d7) "  nf-fa-caret_down

  let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = get(g:, 'WebDevIconsUnicodeDecorateFileNodesExtensionSymbols', {})
  let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['html']     = nr2char(0xe736) " ''
  let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['css']      = nr2char(0xe749) " ''
  let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['markdown'] = nr2char(0xf48a) " ''
  let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['md']       = nr2char(0xf48a) " ''
  let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['txt']      = nr2char(0xf0f6) " ''

  let g:WebDevIconsUnicodeDecorateFileNodesExactSymbols = get(g:, 'WebDevIconsUnicodeDecorateFileNodesExactSymbols', {})
  let g:WebDevIconsUnicodeDecorateFileNodesExactSymbols['pipfile']      = nr2char(0xe73c) " ''
'''

[[plugins]]
repo = 'lambdalisue/vim-devicons-palette'
depends = ['vim-devicons']
hook_add = '''
  let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = get(g:, 'WebDevIconsUnicodeDecorateFileNodesExtensionSymbols', {})
  let g:WebDevIconsUnicodeDecorateFileNodesExactSymbols = get(g:, 'WebDevIconsUnicodeDecorateFileNodesExactSymbols', {})
'''

