 ~/d/g/s/g/s/efm-langserver   …  cat README.md  | markdownlint -s                                                2.6m
stdin: 3: MD013/line-length Line length [Expected: 80; Actual: 154]
stdin: 9: MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
stdin: 12: MD010/no-hard-tabs Hard tabs [Column: 5]
stdin: 14: MD010/no-hard-tabs Hard tabs [Column: 5]
stdin: 17: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '.']
stdin: 24: MD013/line-length Line length [Expected: 80; Actual: 120]
stdin: 30: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '.']
stdin: 37: MD013/line-length Line length [Expected: 80; Actual: 92]
stdin: 43: MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Context: "### Configuration for Markdown..."]
stdin: 43: MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '.']
stdin: 44: MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```vim"]
stdin: 57: MD014/commands-show-output Dollar signs used before commands without showing output [Context: "$ go get github.com/mattn/efm-..."]
stdin: 57: MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
