[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
  " custom glyph
  let g:glyph_palette#palette = get(g:, 'glyph_palette#palette' ,{})

  let g:glyph_palette#palette['GlyphPalette1'] = extend(get(g:glyph_palette#palette, 'GlyphPalette1', []), [])
  let g:glyph_palette#palette['GlyphPalette2'] = extend(get(g:glyph_palette#palette, 'GlyphPalette2', []), [])
  let g:glyph_palette#palette['GlyphPalette3'] = extend(get(g:glyph_palette#palette, 'GlyphPalette3', []), [
    \ nr2char(0xe736),
    \ nr2char(0xe749),
    \ nr2char(0xf48a),
    \ nr2char(0xf0f6),
    \ ])
  let g:glyph_palette#palette['GlyphPalette4'] = extend(get(g:glyph_palette#palette, 'GlyphPalette4', []), [])
  let g:glyph_palette#palette['GlyphPalette5'] = extend(get(g:glyph_palette#palette, 'GlyphPalette5', []), [])
  let g:glyph_palette#palette['GlyphPalette6'] = extend(get(g:glyph_palette#palette, 'GlyphPalette6', []), [])
  let g:glyph_palette#palette['GlyphPalette7'] = extend(get(g:glyph_palette#palette, 'GlyphPalette7', []), [])
  let g:glyph_palette#palette['GlyphPalette8'] = extend(get(g:glyph_palette#palette, 'GlyphPalette8', []), [])
  let g:glyph_palette#palette['GlyphPalette9'] = extend(get(g:glyph_palette#palette, 'GlyphPalette9', []), [])

  augroup vimrc-init_nerdfont
    autocmd!
    autocmd FileType fern     call glyph_palette#apply()
    " autocmd FileType startify call glyph_palette#apply()
  augroup END
'''