type DevIcons = {
  [key: string]: {
    icon: string
    color: Color
  }
}

export const extensions: DevIcons = {
  styl: { icon: "", color: "green" },
  scss: { icon: "", color: "magenta" },
  html: { icon: "", color: "yellow" },
  css: { icon: "", color: "blue" },
  md: { icon: "", color: "yellow" },
  json: { icon: "", color: "yellow" },
  js: { icon: "", color: "yellow" },
  mjs: { icon: "", color: "yellow" },
  jsx: { icon: "", color: "blue" },
  rb: { icon: "", color: "red" },
  php: { icon: "", color: "magenta" },
  py: { icon: "", color: "yellow" },
  pyc: { icon: "", color: "yellow" },
  pyo: { icon: "", color: "yellow" },
  pyd: { icon: "", color: "yellow" },
  conf: { icon: "", color: "white" },
  ini: { icon: "", color: "white" },
  yml: { icon: "", color: "white" },
  yaml: { icon: "", color: "white" },
  bat: { icon: "", color: "white" },
  toml: { icon: "", color: "white" },
  jpg: { icon: "", color: "cyan" },
  jpeg: { icon: "", color: "cyan" },
  bmp: { icon: "", color: "cyan" },
  png: { icon: "", color: "cyan" },
  gif: { icon: "", color: "cyan" },
  ico: { icon: "", color: "cyan" },
  twig: { icon: "", color: "green" },
  cpp: { icon: "", color: "blue" },
  cxx: { icon: "", color: "blue" },
  cc: { icon: "", color: "blue" },
  cp: { icon: "", color: "blue" },
  c: { icon: "", color: "blue" },
  h: { icon: "", color: "white" },
  hpp: { icon: "", color: "white" },
  hxx: { icon: "", color: "white" },
  hs: { icon: "", color: "yellow" },
  lhs: { icon: "", color: "yellow" },
  lua: { icon: "", color: "magenta" },
  java: { icon: "", color: "magenta" },
  sh: { icon: "", color: "magenta" },
  ml: { icon: "λ", color: "yellow" },
  mli: { icon: "λ", color: "yellow" },
  diff: { icon: "", color: "white" },
  sql: { icon: "", color: "blue" },
  clj: { icon: "", color: "green" },
  cljc: { icon: "", color: "green" },
  cljs: { icon: "", color: "green" },
  edn: { icon: "", color: "green" },
  scala: { icon: "", color: "red" },
  go: { icon: "", color: "yellow" },
  dart: { icon: "", color: "white" },
  xul: { icon: "", color: "yellow" },
  sln: { icon: "", color: "magenta" },
  suo: { icon: "", color: "magenta" },
  pl: { icon: "", color: "blue" },
  pm: { icon: "", color: "blue" },
  t: { icon: "", color: "blue" },
  rss: { icon: "", color: "yellow" },
  fsscript: { icon: "", color: "blue" },
  fsx: { icon: "", color: "blue" },
  fs: { icon: "", color: "blue" },
  fsi: { icon: "", color: "blue" },
  rs: { icon: "", color: "yellow" },
  rlib: { icon: "", color: "yellow" },
  d: { icon: "", color: "red" },
  erl: { icon: "", color: "magenta" },
  ex: { icon: "", color: "magenta" },
  exs: { icon: "", color: "magenta" },
  eex: { icon: "", color: "magenta" },
  vim: { icon: "", color: "green" },
  ai: { icon: "", color: "yellow" },
  psd: { icon: "", color: "blue" },
  psb: { icon: "", color: "blue" },
  ts: { icon: "", color: "blue" },
  tsx: { icon: "", color: "blue" },
  jl: { icon: "", color: "magenta" },
  pp: { icon: "", color: "white" },
  vue: { icon: "﵂", color: "green" },
} as const

export const extractColor = () => {
  const colors = Object.entries(extensions).reduce((acc: { [key: string]: Array<string> }, cur) => {
    const [extension, { color }] = cur
    if (acc[color] == null) {
      return { ...acc, ...{ [color]: [`'${extension}'`] } }
    } else {
      acc[color].push(`'${extension}'`)
      return acc
    }
  }, {})

  return `call devicons_palette#settings({
        \\ 'DevIconsPaletteRed': [${colors.red.join(", ")}],
        \\ 'DevIconsPaletteLightRed': [],
        \\ 'DevIconsPaletteDarkRed': [],
        \\ 'DevIconsPaletteGreen': [${colors.green.join(", ")}],
        \\ 'DevIconsPaletteLightGreen': [],
        \\ 'DevIconsPaletteDarkGreen': [],
        \\ 'DevIconsPaletteSeaGreen': [],
        \\ 'DevIconsPaletteBlue': [${colors.blue.join(", ")}],
        \\ 'DevIconsPaletteLightBlue': [],
        \\ 'DevIconsPaletteDarkBlue': [],
        \\ 'DevIconsPaletteSlateBlue': [],
        \\ 'DevIconsPaletteCyan': [${colors.cyan.join(", ")}],
        \\ 'DevIconsPaletteLightCyan': [],
        \\ 'DevIconsPaletteDarkCyan': [],
        \\ 'DevIconsPaletteMagenta': [${colors.magenta.join(", ")}],
        \\ 'DevIconsPaletteLightMagenta': [],
        \\ 'DevIconsPaletteDarkMagenta': [],
        \\ 'DevIconsPaletteYellow': [${colors.yellow.join(", ")}],
        \\ 'DevIconsPaletteLightYellow': [],
        \\ 'DevIconsPaletteBrown': [],
        \\ 'DevIconsPaletteDarkYellow': [],
        \\ 'DevIconsPaletteGray': [],
        \\ 'DevIconsPaletteLightGray': [],
        \\ 'DevIconsPaletteDarkGray': [],
        \\ 'DevIconsPaletteBlack': [],
        \\ 'DevIconsPaletteWhite': [${colors.white.join(", ")}],
        \\ 'DevIconsPaletteOrange': [],
        \\ 'DevIconsPalettePurple': [],
        \\ 'DevIconsPaletteViolet': [],
        \\})
  endif`
}